import { Lesson } from '../types';

export const PERSISTENCE_WITH_SUPABASE_LESSONS: Lesson[] = [
  {
    id: "persistence-with-supabase-manage-data-from-memory-to-database",
    title: "Manage Data — From Memory to Database",
    description: "Transition from in-memory storage to a persistent Postgres database using Supabase.",
    type: "exercise",
    content: `
**User Story:** As a developer, I want to store my application data in a real database so that it survives server restarts and scales with my users.

We are moving from **In-Memory Arrays** to **Supabase** (PostgreSQL).

### Why the Switch?

- **Persistence:** In-memory data vanishes when the server stops. Database data lives forever.
- **Power:** You get powerful filtering, sorting, and relations out of the box.
- **Scalability:** Arrays get slow with thousands of items; databases handle millions.

### The Architecture

Instead of a variable in your file, your Express server will act as a **Client** that talks to the Supabase **Server**.
`
  },
  {
    id: "persistence-with-supabase-setup-supabase-in-node",
    title: "Setup Supabase in Node",
    description: "Transition from in-memory storage to a persistent Postgres database using Supabase.",
    type: "exercise",
    content: `
**User Story:** As a developer, I need to install the necessary libraries and configure my environment variables so that my server can authenticate with the database.

### Instructions

1. **Install Dependencies:**
   Run \`npm install @supabase/supabase-js dotenv\` in your terminal.

2. **Create \`.env\` file:**
   Create a file named \`.env\` in your root directory. Add your project URL and Key (found in your Supabase Dashboard settings).

\`\`\`env
SUPABASE_URL=https://your-project-url.supabase.co
SUPABASE_KEY=your-anon-public-key
\`\`\`

3. **Configure the Client:**
   Create a new file \`src/supabase.js\` to initialize and export the connection.

\`\`\`javascript:Show Me: Supabase Configuration
// src/supabase.js
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;

const supabase = createClient(supabaseUrl, supabaseKey);

export default supabase;
\`\`\`
`
    ,codeSnippets: [
      {
        language: "javascript",
        summary: "Show Me: Supabase Configuration",
        code: `
// src/supabase.js
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;

const supabase = createClient(supabaseUrl, supabaseKey);

export default supabase;
`,
        description: "Snippet for: Show Me: Supabase Configuration"
      }
    ]
  },
  {
    id: "persistence-with-supabase-design-your-table",
    title: "Design Your Table",
    description: "Transition from in-memory storage to a persistent Postgres database using Supabase.",
    type: "exercise",
    content: `
**User Story:** As an architect, I want to define the schema of my database table so that Supabase knows how to store my data.

### Instructions

1. **Go to Supabase Dashboard:** Open the Table Editor.
2. **Create a New Table:** Name it according to your resource (e.g., \`books\`, \`courses\`).
3. **Add Columns:** Match the fields you need.
   - \`id\` (int8, Primary Key, Auto-increment) - **Let Supabase handle this!**
   - \`title\` (text)
   - \`author\` (text)
   - \`price\` (float4)

### 💡 Code Hints

Even though the DB handles the schema, keep a reference object in your code for testing:

\`\`\`javascript:Show Me: Reference Object
// For reference only - this is now a Table in Supabase!
const bookShape = {
  // id: generated by DB
  title: 'The Great Gatsby', // text
  author: 'F. Scott Fitzgerald', // text
  price: 10.99 // float
};
\`\`\`
`
    ,codeSnippets: [
      {
        language: "javascript",
        summary: "Show Me: Reference Object",
        code: `
// For reference only - this is now a Table in Supabase!
const bookShape = {
  // id: generated by DB
  title: 'The Great Gatsby', // text
  author: 'F. Scott Fitzgerald', // text
  price: 10.99 // float
};
`,
        description: "Snippet for: Show Me: Reference Object"
      }
    ]
  },
  {
    id: "persistence-with-supabase-connect-client-to-server",
    title: "Connect Client to Server",
    description: "Transition from in-memory storage to a persistent Postgres database using Supabase.",
    type: "exercise",
    content: `
**User Story:** As a developer, I want to import my Supabase client into my server file so I can start making queries.

### Instructions

1. Open \`src/index.js\`.
2. Import the \`supabase\` client you created in the setup step.
3. Ensure \`express.json()\` middleware is used (crucial for passing data to Supabase).

\`\`\`javascript:Show Me: Import Logic
import express from 'express';
import supabase from './supabase.js'; // Import the connection

const app = express();
app.use(express.json());
\`\`\`
`
    ,codeSnippets: [
      {
        language: "javascript",
        summary: "Show Me: Import Logic",
        code: `
import express from 'express';
import supabase from './supabase.js'; // Import the connection

const app = express();
app.use(express.json());
`,
        description: "Snippet for: Show Me: Import Logic"
      }
    ]
  },
  {
    id: "persistence-with-supabase-build-get-resource",
    title: "Build GET Resource",
    description: "Transition from in-memory storage to a persistent Postgres database using Supabase.",
    type: "exercise",
    content: `
**User Story:** As a client, I want to request a list of all resources from the database so that I can display them.

### Instructions

1. Add a \`GET\` route.
2. Use \`await supabase.from('your_table').select('*')\`.
3. Handle errors: If the database fails, return a \`500\`.
4. Return \`data\` with status \`200\`.

\`\`\`javascript:Show Me: GET with Supabase
app.get('/books', async (req, res) => {
  const { data, error } = await supabase
    .from('books')
    .select('*');

  if (error) {
    return res.status(500).json({ error: error.message });
  }

  res.json(data);
});
\`\`\`
`
    ,codeSnippets: [
      {
        language: "javascript",
        summary: "Show Me: GET with Supabase",
        code: `
app.get('/books', async (req, res) => {
  const { data, error } = await supabase
    .from('books')
    .select('*');

  if (error) {
    return res.status(500).json({ error: error.message });
  }

  res.json(data);
});
`,
        description: "Snippet for: Show Me: GET with Supabase"
      }
    ]
  },
  {
    id: "persistence-with-supabase-build-post-resource",
    title: "Build POST Resource",
    description: "Transition from in-memory storage to a persistent Postgres database using Supabase.",
    type: "exercise",
    content: `
**User Story:** As a client, I want to insert new rows into the database so that the data is permanently stored.

### Instructions

1. Create a \`POST\` route.
2. Use \`await supabase.from('your_table').insert(req.body).select()\`.
3. **Crucial:** Add \`.select()\` at the end of the chain to return the newly created item (including its generated ID).
4. Return the first item of the \`data\` array with status \`201\`.

\`\`\`javascript:Show Me: POST with Supabase
app.post('/books', async (req, res) => {
  const { data, error } = await supabase
    .from('books')
    .insert(req.body)
    .select(); // Returns the created record

  if (error) {
    return res.status(500).json({ error: error.message });
  }

  // Supabase returns an array, we want the single object
  res.status(201).json(data[0]);
});
\`\`\`
`
    ,codeSnippets: [
      {
        language: "javascript",
        summary: "Show Me: POST with Supabase",
        code: `
app.post('/books', async (req, res) => {
  const { data, error } = await supabase
    .from('books')
    .insert(req.body)
    .select(); // Returns the created record

  if (error) {
    return res.status(500).json({ error: error.message });
  }

  // Supabase returns an array, we want the single object
  res.status(201).json(data[0]);
});
`,
        description: "Snippet for: Show Me: POST with Supabase"
      }
    ]
  },
  {
    id: "persistence-with-supabase-enforce-basic-validation",
    title: "Enforce Basic Validation",
    description: "Transition from in-memory storage to a persistent Postgres database using Supabase.",
    type: "exercise",
    content: `
**User Story:** As a developer, I want to validate data *before* sending it to the database to save bandwidth and ensure data integrity.

### Instructions

1. Check if required fields are present in \`req.body\`.
2. If data is missing, short-circuit the function and return \`400\` *before* calling Supabase.

\`\`\`javascript:Show Me: Validation Check
app.post('/books', async (req, res) => {
  // Validate BEFORE talking to the database
  if (!req.body.title || !req.body.author) {
    return res.status(400).json({ error: 'Title and Author are required' });
  }

  // ... proceed to supabase insert ...
});
\`\`\`
`
    ,codeSnippets: [
      {
        language: "javascript",
        summary: "Show Me: Validation Check",
        code: `
app.post('/books', async (req, res) => {
  // Validate BEFORE talking to the database
  if (!req.body.title || !req.body.author) {
    return res.status(400).json({ error: 'Title and Author are required' });
  }

  // ... proceed to supabase insert ...
});
`,
        description: "Snippet for: Show Me: Validation Check"
      }
    ]
  },
  {
    id: "persistence-with-supabase-handling-auto-generated-ids",
    title: "Handling Auto-Generated IDs",
    description: "Transition from in-memory storage to a persistent Postgres database using Supabase.",
    type: "exercise",
    content: `
**User Story:** As a developer, I want to rely on the database to generate unique IDs so that I don't have to manage complex ID logic in my code.

### Concept Change

In the in-memory lesson, we manually generated IDs using \`randomUUID()\`.
**With Supabase, we stop doing this.**

Postgres (the DB behind Supabase) automatically assigns a unique \`id\` when you \`.insert()\`. Your job is simply to read it back using \`.select()\`.
`
  },
  {
    id: "persistence-with-supabase-implement-get-by-id",
    title: "Implement GET by ID",
    description: "Transition from in-memory storage to a persistent Postgres database using Supabase.",
    type: "exercise",
    content: `
**User Story:** As a client, I want to query the database for a specific row so that I can view its details.

### Instructions

1. Define a route \`/resource/:id\`.
2. Use \`.select('*').eq('id', req.params.id)\`.
3. Use \`.single()\` to tell Supabase we expect exactly one result.
4. Handle the error (Supabase returns a specific error code for "Row not found").

\`\`\`javascript:Show Me: GET Single Row
app.get('/books/:id', async (req, res) => {
  const { data, error } = await supabase
    .from('books')
    .select('*')
    .eq('id', req.params.id)
    .single(); // Efficiently fetches just one

  if (error) {
    return res.status(404).json({ error: 'Book not found' });
  }

  res.json(data);
});
\`\`\`
`
    ,codeSnippets: [
      {
        language: "javascript",
        summary: "Show Me: GET Single Row",
        code: `
app.get('/books/:id', async (req, res) => {
  const { data, error } = await supabase
    .from('books')
    .select('*')
    .eq('id', req.params.id)
    .single(); // Efficiently fetches just one

  if (error) {
    return res.status(404).json({ error: 'Book not found' });
  }

  res.json(data);
});
`,
        description: "Snippet for: Show Me: GET Single Row"
      }
    ]
  },
  {
    id: "persistence-with-supabase-implement-delete-by-id",
    title: "Implement DELETE by ID",
    description: "Transition from in-memory storage to a persistent Postgres database using Supabase.",
    type: "exercise",
    content: `
**User Story:** As a client, I want to remove a row from the database so that outdated information is permanently deleted.

### Instructions

1. Define a \`DELETE\` route.
2. Use \`await supabase.from('your_table').delete().eq('id', req.params.id)\`.
3. Check for errors.

\`\`\`javascript:Show Me: DELETE Row
app.delete('/books/:id', async (req, res) => {
  const { error } = await supabase
    .from('books')
    .delete()
    .eq('id', req.params.id);

  if (error) {
    return res.status(500).json({ error: error.message });
  }

  res.status(200).json({ message: 'Book deleted successfully' });
});
\`\`\`
`
    ,codeSnippets: [
      {
        language: "javascript",
        summary: "Show Me: DELETE Row",
        code: `
app.delete('/books/:id', async (req, res) => {
  const { error } = await supabase
    .from('books')
    .delete()
    .eq('id', req.params.id);

  if (error) {
    return res.status(500).json({ error: error.message });
  }

  res.status(200).json({ message: 'Book deleted successfully' });
});
`,
        description: "Snippet for: Show Me: DELETE Row"
      }
    ]
  }
];
